net-il-mio-fotoalbum/Models/Foto.cs
using System.ComponentModel.DataAnnotations;

namespace net_il_mio_fotoalbum.Models
{
    public class Foto
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Il titolo è necessario")]
        [StringLength(40, ErrorMessage = "Il titolo deve avere max 40 caratteri")]
        public string Titolo { get; set; }
        [Required(ErrorMessage = "La descrizione è necessaria")]
        public string Descrizione { get; set; }
        public bool Visibile { get; set; }

        public byte[]? ImageFile { get; set; }
        public string ImgSrc => ImageFile != null ? $"data:image/png;base64,{Convert.ToBase64String(ImageFile)}" : "";

        // classe ingredienti con collegamento N-N
        public List<Categoria>? Categorie { get; set; }

        public Foto() { }

        public Foto(string titolo, string descrizione, bool visibile, List<Categoria> categorie)
        {
            this.Titolo = titolo;
            this.Descrizione = descrizione;
            this.Visibile = visibile;
            this.Categorie = categorie;
        }
        // funzione che mi stampi tutte le categorie
        public string TutteLeCategorie()
        {
            return string.Join(", ", Categorie.Select(c => c.Nome));
        }
    }

}

net-il-mio-fotoalbum/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using net_il_mio_fotoalbum.Data;
using net_il_mio_fotoalbum.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Index()
        {
            return View("Index", CategoriaManager.TutteCategorie());
        }
        [HttpGet]
        public IActionResult Create()
        {
            Categoria categoria = new Categoria();

            return View(categoria);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categoria data)
        {
            if (!ModelState.IsValid)
            {
                return View(data);
            }
            CategoriaManager.InserisciCategoria(data);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (!CategoriaManager.EliminaCategoria(id))
            {
                return NotFound();
            }
            return RedirectToAction("Index");


        }
    }
}

net-il-mio-fotoalbum/Controllers/FotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using net_il_mio_fotoalbum.Data;
using net_il_mio_fotoalbum.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    public class FotoController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public FotoController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View(FotoManager.TutteFoto());
        }
        public IActionResult Details(int id)
        {
            var foto = FotoManager.CercaPerId(id);
            if (foto == null)
                return NotFound();
            return View(foto);
        }
        [HttpGet]
        public IActionResult Create()
        {
            FotoFormModel model = new FotoFormModel(new Foto(), FotoFormModel.CreaCategorie() );
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FotoFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.Categorie = FotoFormModel.CreaCategorie();
                data.SetImage();
                return View(data);
            }
            data.SetImage();
            FotoManager.InserisciFoto(data.Foto, data.SelezionaCategorie);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var fotoDaModificare = FotoManager.CercaPerId(id);
            if (fotoDaModificare == null)
                return NotFound();
            FotoFormModel model = new FotoFormModel(fotoDaModificare, FotoFormModel.CreaCategorie());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, FotoFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.Categorie = FotoFormModel.CreaCategorie();
                data.SetImage();
                return View(data);
            }

            if (!FotoManager.ModificaFoto(id, data.Foto.Titolo, data.Foto.Descrizione, data.Foto.Visibile, data.SelezionaCategorie, data.SetImage()))
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (!FotoManager.EliminaFoto(id))
                return NotFound();
            return RedirectToAction("Index");
        }
    }
}

net-il-mio-fotoalbum/Views/Foto/Create.cshtml
@model FotoFormModel

<div class="text-end">
    <a href="@Url.Action("index", "Foto")" class="fs-2 me-md-2"><i class="bi bi-arrow-left"></i></a>
</div>

<div class="text-center container-xxl">
    <form asp-controller="Foto" asp-action="Create" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div class="m-5">
            <label for="Titolo" class="form-label "><strong>Titolo:</strong></label>
            <input asp-for="Foto.Titolo" type="text" class="form-control w-50 my-0 mx-auto" id="Titolo" placeholder="Inserisci titolo">
            <span asp-validation-for="Foto.Titolo" class=" d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
        <div class="m-5">
            <label for="Descrizione" class="form-label"><strong>Descrizione</strong></label>
            <textarea asp-for="Foto.Descrizione" class="form-control w-50 my-0 mx-auto" id="Descrizione" style="height: 100px" placeholder="Inserisci Descrizione"></textarea>
            <span asp-validation-for="Foto.Descrizione" class="d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
       <div class="m-5">
           <label class="form-label" for="Visibile"><strong>Visibile:</strong></label>
           <input asp-for="Foto.Visibile" type="checkbox" class="form-check-input" id="Visibile">
       </div>
        <div class="m-5">
            <label class="form-label d-block" for="Categorie"><strong> Categorie:</strong></label>
            <div class="d-flex flex-wrap align-items-center justify-content-center gap-2">
                @for (int i = 0; i < Model.Categorie.Count; i++)
                {

                    <input type="checkbox" name="SelezionaCategorie" value="@Model.Categorie[i].Value"
                           @(Model.SelezionaCategorie != null && Model.SelezionaCategorie.Contains(Model.Categorie[i].Value) ? "checked" : "") />
                    @Model.Categorie[i].Text
                }
            </div>
            <span asp-validation-for="Foto.Categorie" class="d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
        <div class="m-5">
            <div class="form-field d-flex flex-column  align-items-center gap-3">
                <img style="width:200px;" src="@Model.Foto.ImgSrc">
                <label asp-for="ImageFormFile">Carica un immagine</label>
                <input type="file" asp-for="ImageFormFile" />
            </div>
        </div>
        <div class="text-end">
            <input type="submit" class="btn btn-primary me-2 mb-5" value="Crea Prodotto">
        </div>
    </form>
</div>

net-il-mio-fotoalbum/Views/Foto/Details.cshtml
@model Foto

@{
    ViewData["Title"] = "Dettaglio";
}
<div class="text-end">
    <a href="@Url.Action("index", "Foto")" class="fs-2 me-md-2"><i class="bi bi-arrow-left"></i></a>
</div>
<div class="text-center container-xxl">

    <h1 class="mb-4"> @ViewData["Title"]</h1>

    <ul class="list-unstyled d-grid gap-3">
        <li>Id: @Model.Id</li>
        <li>Nome: @Model.Titolo</li>
        <li>Descrizione: @Model.Descrizione</li>
        <li>Categorie: @Model.TutteLeCategorie()</li>
        <li>Visibile: @Model.Visibile</li>
        
        <li>Immagine: <img style="width:200px;" src="@Model.ImgSrc">
        </li>
    </ul>

</div>

net-il-mio-fotoalbum/Views/Foto/Index.cshtml
@model List<Foto>
@{
    ViewData["Title"] = "Foto";
}


<div class="text-center container-xxl">
    <h1 style="color: var(--my-text-color-primary);">@ViewData["Title"]</h1>


    <div class="d-flex justify-content-between mb-3">
        @if (User.IsInRole("Admin"))
        {
            <a href="@Url.Action("Index", "Categoria")" class="btn btn-primary me-md-2 text-white">Mostra le categorie</a>
            <input type="text" id="Filter" placeholder="Filtra per Titolo" />
            <a href="@Url.Action("Create", "Foto")" class="btn btn-primary me-md-2 text-white">Aggiungi Foto</a>
        }
    </div>
    @if (Model.Count == 0)
    {
        <h2 class="bg-gradient">Nessuna Foto disponibile</h2>
    }
    else
    {

        <table class="table border-0">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Titolo</th>
                    <th class="d-none d-md-table-cell" scope="col">Descrizione</th>
                    <th  scope="col">Visibile</th>
                    <th class="d-none d-md-table-cell" scope="col">Immagine</th>

                    @if (User.IsInRole("Admin"))
                    {
                        <th scope="col">Dettaglio</th>
                        <th scope="col">Modifica</th>
                        <th scope="col">Elimina</th>
                    }

                </tr>
            </thead>
            <tbody style="vertical-align:unset;">
                @{
                    int i = 1;
                    foreach (var item in Model)
                    {

                                <tr class="MyFoto">
                                    <th scope="row">@i</th>
                                    <td class="FilterText">@item.Titolo</td>
                                    <td class="d-none d-md-table-cell">@item.Descrizione</td>
                                    @if (item.Visibile)
                                    {
                                        <td><i class="bi bi-check-lg"></i></td>
                                    }
                                    else
                                    {
                                        <td><i class="bi bi-x-lg"></i></td>
                                    }


                                    @if (item.ImageFile == null)
                                    {
                                        <td class="d-none d-md-table-cell">
                                            <img style="width: 150px; height: 100px" src="~/img/image-nofound.jpg" alt=@item.Titolo>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="d-none d-md-table-cell">
                                            <img style="width: 150px; height: 100px" src="@item.ImgSrc" alt=@item.Titolo>
                                        </td>
                                    }
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <td>
                                            <a class="text-black" href="@Url.Action("Details", "Foto", new { id=item.Id} )"> <i class="bi bi-ticket-detailed"></i> </a>
                                        </td>

                                        <td>
                                            <a class="text-black" href="@Url.Action("Update", "Foto", new { id=item.Id} )"> <i class="bi bi-pencil-square"></i> </a>
                                        </td>
                                        <td class="d-flex align-items-center justify-content-around border-0">
                                            <form asp-controller="Foto" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                                @Html.AntiForgeryToken()
                                                <button type="submit" class="btn"><i class="bi bi-trash"></i> </button>
                                            </form>
                                        </td>

                                    }

                                </tr>

                        i++;
                    }
                }
            </tbody>
        </table>
    }
</div>
<script>
    document.getElementById('Filter').addEventListener('keyup', function () {
        var filter = this.value.toLowerCase();
        var fotos = document.querySelectorAll('.MyFoto');
        fotos.forEach(function (foto) {
            var text = foto.querySelector('.FilterText').innerText.toLowerCase();
            if (text.includes(filter)) {
                foto.classList.remove('d-none');
            } else {
                foto.classList.add('d-none');
            }
        });

    });
</script>

net-il-mio-fotoalbum/Views/Foto/Update.cshtml
@model FotoFormModel

<div class="text-end">
    <a href="@Url.Action("index", "Foto")" class="fs-2 me-md-2"><i class="bi bi-arrow-left"></i></a>
</div>

<div class="text-center container-xxl">
    <form asp-controller="Foto" asp-action="Update" asp-route-id="@Model.Foto.Id" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div class="m-5">
            <label for="Titolo" class="form-label "><strong>Titolo:</strong></label>
            <input asp-for="Foto.Titolo" type="text" class="form-control w-50 my-0 mx-auto" id="Titolo" placeholder="Inserisci titolo">
            <span asp-validation-for="Foto.Titolo" class=" d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
        <div class="m-5">
            <label for="Descrizione" class="form-label"><strong>Descrizione</strong></label>
            <textarea asp-for="Foto.Descrizione" class="form-control w-50 my-0 mx-auto" id="Descrizione" style="height: 100px" placeholder="Inserisci Descrizione"></textarea>
            <span asp-validation-for="Foto.Descrizione" class="d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
        <div class="m-5">
            <label class="form-label" for="Visibile"><strong>Visibile:</strong></label>
            <input asp-for="Foto.Visibile" type="checkbox" class="form-check-input" id="Visibile">
        </div>
        <div class="m-5">
            <label class="form-label d-block" for="Categorie"><strong> Categorie:</strong></label>
            <div class="d-flex flex-wrap align-items-center justify-content-center gap-2">
                @for (int i = 0; i < Model.Categorie.Count; i++)
                {

                    <input type="checkbox" name="SelezionaCategorie" value="@Model.Categorie[i].Value"
                           @(Model.SelezionaCategorie != null && Model.SelezionaCategorie.Contains(Model.Categorie[i].Value) ? "checked" : "") />
                    @Model.Categorie[i].Text
                }
            </div>
            <span asp-validation-for="Foto.Categorie" class="d-inline-block mt-2 text-light bg-primary text-uppercase px-5"></span>
        </div>
        <div class="m-5">
            <div class="form-field d-flex flex-column  align-items-center gap-3">
                <img style="width:200px;" src="@Model.Foto.ImgSrc">
                <label asp-for="ImageFormFile">Carica un immagine</label>
                <input type="file" asp-for="ImageFormFile" />
            </div>
        </div>
        <div class="text-end">
            <input type="submit" class="btn btn-primary me-2 mb-5" value="Modifica Prodotto">
        </div>
    </form>
</div>